version: '3'

services:

  nginx:
    image: nginx:1.24.0
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../static:/var/www/html
    ports:
      - "14433:14433"
    depends_on:
      - web

  web:
    image: 9527233/chatgptscan-web:1.0.0
    container_name: web
    volumes:
      - ../web:/app
    depends_on:
      - db

  db:
    image: mysql:8.0.32
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ChatGPTScan
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/my.cnf
    ports:
      - "3306:3306"
